knpu_oauth2_client:
    clients:
        vkontakte_client:
            type: vkontakte
            client_id: '%env(VK_API_ID)%'
            client_secret: '%env(VK_SECRET_KEY)%'
            redirect_route: connect_vkontakte_check
            redirect_params: { }
